### ISSUE TITLE
Issue with the switches

### ISSUE THREAD

**Issue by xpertcrush** [OpenI6X/opentx#170] opened 2022-02-21 16:22 UTC
When you set up your model after a while you lose your switches on the display page as well as they don't react to your input when you try to arm or do other things with switches. few days ago I had this similar issue but I thought maybe I messed up something but today I face the issue again even after resetting the eeprom. It was working fine until yesterday I turned it off but today when I turn it on again and try to arm my quad using the switches it didn't respond so I checked the display and I found there is no switches anymore in input switches are set correctly and even on mixer switches are set correctly using the inputs but if I try to change input values in the mixture to switches I don't see any switches there if I reset the eepROM then I will definitely find the switches again
**To Reproduce**

**Expected behavior**

**Screenshots**

https://youtu.be/_lcqsMPcbrg

**General information**
 - OpenTX version (1.3.0)

**Comment by ajjjjjjjj** [comment] 2022-02-21 17:03
Please describe reproduction steps. What have you changed in your setup then how do you shutdown - was it soft shutdown before powering, etc.

**Comment by xpertcrush** [comment] 2022-02-21 17:07
Yes it was soft shutdown yesterday and i just used it for 20 minutes for flying, no settings were changed. Do not know the step to reproduce, it just happened twice to me. It happened randomly, first time it was in a day, today it happened after working fine for 3 days.

**Comment by tn2009** [comment] 2022-02-21 17:17
I had this after restoring EEPROM.bin

**Comment by ajjjjjjjj** [comment] 2022-03-04 20:26
Please add as much detail as you can, were you using USB / ELRS meanwhile? Which build exactly you are using? etc. Try to create reproduction scenario.

**Comment by ajjjjjjjj** [comment] 2022-03-19 20:10
Please try this build and report back:
[opentx-i6x-dev-eeprom.zip](https://github.com/OpenI6X/opentx/files/8310019/opentx-i6x-dev-eeprom.zip)

**Comment by ajjjjjjjj** [comment] 2022-05-05 21:27
Closing because stalled.

**Closed by ajjjjjjjj** 2022-05-05 21:27 UTC
