### ISSUE TITLE
Bootloop problem

### ISSUE THREAD

**Issue by proffesionaldumbass** [OpenI6X/opentx#323] opened 2022-12-17 22:00 UTC
When i first flashed the remote everything was working great, but after a power cycle the Failsafe not set warning came up as expected, i cleared it but then after a few seconds it popped up again and reset everything, this happens over and over so i cant set failsafe up because there is not enough time. I tried rebooting, turning on dfu mode but nothing works. I will try to reflash tomorrow but my first attempt failed so i dont have high hopes

**Comment by ajjjjjjjj** [comment] 2022-12-18 09:00
Try 1.8.0

**Comment by proffesionaldumbass** [comment] 2022-12-18 09:11
Unfortunately while flashing the display gave out, i changed it but nothing happened so the display driver is bricked. But from the sound the firmware is working allright now

**Comment by ajjjjjjjj** [comment] 2022-12-18 09:49
I'm not 100% sure but we had blank display issues before and similar reboot problems and it was faulty MCU problem.
Are you able to bind to receiver on original firmware?

**Comment by Bash365** [comment] 2022-12-18 09:51
I have the same issue

**Comment by ajjjjjjjj** [comment] 2022-12-18 10:02
@bash, good that you reported, you cannot expect something being fixed without letting know that it is broken.

**Comment by Bash365** [comment] 2022-12-18 10:05
True that. I thought I'd wait a bit to see if anyone else had the same
issue. Mine happened after a flash from original  firmware as well forgot
to mention it

**Comment by ajjjjjjjj** [comment] 2022-12-20 16:12
@proffesionaldumbass , @Bash365 , can you try on this one?
https://output.circle-artifacts.com/output/job/da2ab32e-56be-432f-8d24-e0e3b9c31609/artifacts/0/output/openi6x_en_221220.bin

**Comment by Bash365** [comment] 2022-12-20 16:53
Will try it shortly Sent from Mail for Windows From: JanekSent: Tuesday, 20 December 2022 18:12To: OpenI6X/opentxCc: Bash365; MentionSubject: Re: [OpenI6X/opentx] Failsafe not set warning keeps popping up (Issue ***@***.*** , @Bash365 , can you try on this one?https://output.circle-artifacts.com/output/job/da2ab32e-56be-432f-8d24-e0e3b9c31609/artifacts/0/output/openi6x_en_221220.bin—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Bash365** [comment] 2022-12-20 17:20
Tried it. Doesn't boot up. Screen stays blank

**Comment by ajjjjjjjj** [comment] 2022-12-20 17:33
1.8.0 is working?

**Comment by Bash365** [comment] 2022-12-20 18:00
Yes 1.8.0 works but with no proper working ppm and no afhds support

**Comment by ajjjjjjjj** [comment] 2022-12-22 10:26
If you are powering it with 2S directly there is a chance that you damaged your radio and now 1.8.0 or original software may also not work correctly, like unable to connect to receiver.

**Comment by Bash365** [comment] 2022-12-22 14:10
> If you are powering it with 2S directly there is a chance that you damaged your radio and now 1.8.0 or original software may also not work correctly, like unable to connect to receiver.

Thats 6.6v life its not a lipo. so the voltage i believe is fine. I already have stated that I have no other issues with the radio using original firmware and also 1.8.0 so i believe the issue is not with damage to my radio as it doesnt display any other issues as you have described. 
this isnt my thread as well so im not the only person with this issue.

**Comment by Bash365** [comment] 2022-12-22 14:12
Also telling me I damaged my radio seems like its the go to excuse for certain features of a aftermarket open source software. Its the software thats the issue not the hardware in this case

**Comment by ajjjjjjjj** [comment] 2022-12-22 15:20
> Thats 6.6v life its not a lipo. so the voltage i believe is fine. (...)
>Also telling me I damaged my radio seems like its the go to excuse for certain features of a aftermarket open source software. Its the software thats the issue not the hardware in this case

LiFePO4 2S fully charged is about 7.3V, well above LDO spec.
The only change that could trigger boot loop in 1.9.0 is failure of initializing additional timer - the one responsible for PPM.
This is not a valid place for your comments on opensource community.

**Comment by Bash365** [comment] 2022-12-22 23:59
Well I apologize if I hurt your feelings but there's no other forums nor is there anything else linked to this forum or related in any way where I can vent how I feel about opentx. I didnt mention the community as a whole. I did however mention I'm using a module so possibly this is the cause as it's directly related and connected to the ppm out.

**Comment by Bash365** [comment] 2022-12-23 00:01
I'll continue to wait until all the features have been implemented that I need and when all the bugs are ironed out. Until then I'm happy using original firmware. NO ISSUES AT ALL!!

**Comment by ajjjjjjjj** [comment] 2022-12-23 09:34
No need to apologize, no feelings hurt. 
> there's no other forums nor is there anything else linked to this forum or related in any way where I can vent how I feel about opentx

Main page readme links to groups on: Telegram, Discord and RCGroups. 

@proffesionaldumbass, there were similar stories in https://github.com/OpenI6X/opentx/issues/204 and https://github.com/OpenI6X/opentx/issues/246 Can you confirm your case is similar and/or you are powering from 2S lipo direclty?

**Comment by proffesionaldumbass** [comment] 2022-12-23 10:57
I was powering it off of the standart 4x aa batteries, so no issue there

**Closed** 2023-01-08 07:51 UTC
